version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
    depends_on:
      - db
    ports:
      - 8081:80
    networks:
      - dev_pos_dev
  db:
    env_file:
      - .env
    container_name: db
    ports:
      - '3306:3306'
    image: mysql
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dev_pos_dev
networks:
  dev_pos_dev:
    name: dev_pos_dev
    driver: bridge
